- name: Install and configure self-hosted GitHub runner containers
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  any_errors_fatal: true
  tasks:
    - name: Install Docker
      ansible.builtin.import_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose_plugin: true
      tags: [ docker ]

    - name: Load groups
      ansible.builtin.getent:
        database: group
        split: ':'
        key: "docker"
      tags: [ docker-stack ]

    - name: Set docker group id to facts
      ansible.builtin.set_fact:
        docker_gid: "{{ ansible_facts.getent_group['docker'][1] }}"
      tags: [ docker-stack ]

    - name: Install required python packages
      ansible.builtin.package:
        name:
          - python3-docker
          - python3-compose
        state: present
        tags: [ docker-stack ]

    - name: Set up runners compose stack
      community.docker.docker_compose:
        project_name: github-runners
        definition: "{{ lookup('template', 'templates/runners-docker-compose.yml.j2') | from_yaml }}"
        recreate: always
        state: present
      tags: [ docker-stack ]
